### ISSUE TITLE
Unable to execute  ros2 launch br2_tiago for foxy

### ISSUE THREAD

**Issue by coredmas** [fmrico/book_ros2#20]
# Important!!!
- [x] I have checked that this issue/bug/fix/correction has not been already created before in open or closed issues.

# Type of bug
- [ ] A) Typo/error in Figure/text
- [ ] B) Bug in code
- [ ] C) General comment, recommendation or petition 

# Issue Description
Hello,
I have problems with chapter 2 " ros2 launch br2_tiago sim.launch.py".
I get the following error messages:

ros2 launch br2_tiago sim.launch.py world:=small_office
[INFO] [launch]: All log files can be found below /home/dmas/.ros/log/2023-05-21-20-46-57-013635-ubuntu-box-6636
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure('executed command failed. Command: /opt/ros/foxy/lib/xacro/xacro /home/dmas/ros2_ws/install/tiago_description/share/tiago_description/robots/tiago.urdf.xacro laser_model:=sick-571 arm:=right-arm end_effector:=pal-hey5 ft_sensor:=schunk-ft camera_model:=orbbec-astra')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 7 more times]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 444, in execute
    self._perform_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 399, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 164, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 71, in evaluate_parameter_dict
    evaluated_value = perform_substitutions(context, list(value))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_context.py", line 232, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/substitutions/command.py", line 116, in perform
    raise SubstitutionFailure(f'executed command failed. Command: {command_str}')
launch.substitutions.substitution_failure.SubstitutionFailure: executed command failed. Command: /opt/ros/foxy/lib/xacro/xacro /home/dmas/ros2_ws/install/tiago_description/share/tiago_description/robots/tiago.urdf.xacro laser_model:=sick-571 arm:=right-arm end_effector:=pal-hey5 ft_sensor:=schunk-ft camera_model:=orbbec-astra
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=RuntimeError('Signal event received before subprocess transport available.')>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/opaque_function.py", line 75, in execute
    return self.__function(context, *self.__args, **self.__kwargs)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/actions/execute_process.py", line 443, in __on_signal_process_event
    raise RuntimeError('Signal event received before subprocess transport available.')
RuntimeError: Signal event received before subprocess transport available.
[INFO] [gzserver-1]: process started with pid [6643]
[INFO] [gzclient   -2]: process started with pid [6645]
[INFO] [gzserver-1]: sending signal 'SIGINT' to process[gzserver-1]
[ERROR] [gzclient   -2]: process[gzclient   -2] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [gzserver-1]: process[gzserver-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gzclient   -2]: sending signal 'SIGTERM' to process[gzclient   -2]
[INFO] [gzserver-1]: sending signal 'SIGTERM' to process[gzserver-1]
[ERROR] [gzclient   -2]: process has died [pid 6645, exit code -15, cmd 'gzclient   '].
[ERROR] [gzserver-1]: process has died [pid 6643, exit code -15, cmd 'gzserver /home/dmas/ros2_ws/install/pal_gazebo_worlds/share/pal_gazebo_worlds/worlds/small_office.world                                                                      -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so   -s libgazebo_ros_force_system.so       '].

# A) *Typo/Error Description*
(Remove section if not applicable)

## Screenshot
If applicable, add screenshots to help explain the problem.

## Proposal
Proposal to fix or correct the issue

# B) *Bug Description*
(Remove section if not applicable)

## how to reproduce
2. Type on '....'
3. Execute '....'

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu 20.04]
 - ROS2 Distro [Foxy]

**Comment by fmrico** [comment]
Hi @coredmas 

I have just checked it and it is working in a fresh installation. Does the problem persist for you?

Best

**Comment by phil123456** [comment]
as for me, I cannot even build it

I also had to install a gazillion tons of packages to avoid missing packages
maybe you should try a fresh 20.04 install in a VM like I did, tons of things are missing

I also had to comment these missing **ament_auto_find_test_dependencies** functions in the make files

https://robotics.stackexchange.com/questions/103945/ubuntu-20-04-64bits-unknown-cmake-command-ament-auto-find-test-dependencies

play_motion2_msgs is nowhere to be found

```
--- stderr: tiago_gazebo                            
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findplay_motion2_msgs.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "play_motion2_msgs", but CMake did not find one.

  Could not find a package configuration file provided by "play_motion2_msgs"
  with any of the following names:

    play_motion2_msgsConfig.cmake
    play_motion2_msgs-config.cmake

  Add the installation prefix of "play_motion2_msgs" to CMAKE_PREFIX_PATH or
  set "play_motion2_msgs_DIR" to a directory containing one of the above
  files.  If "play_motion2_msgs" provides a separate development package or
  SDK, be sure it has been installed.
---

```

**Comment by fmrico** [comment]
Hi, 

`foxy-devel` branch does not contain any dependency on `play_motion2_*` packages. So, @phil123456 's reply is not related to @coredmas 's problem.

`main` and `humble-devel` have dependencies with `play_motion2_*` packages, but you can easily install them by 

```
sudo apt install ros-humble-play-motion2*
```

**Comment by fmrico** [comment]
Closing this issue, as @coredmas are not showing activity. Please, reopen if you still have problems
